# Generated by Django 5.0.6 on 2024-07-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiantil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='updated_at',
        ),
    ]
