# Generated by Django 5.0.6 on 2024-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
